# Generated by Django 2.2.7 on 2019-12-10 23:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_text', models.CharField(max_length=50)),
                ('belongs_to', models.CharField(max_length=150)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('occurrence', models.IntegerField()),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2019, 12, 10, 5, 0, tzinfo=utc), verbose_name='date habit was last changed')),
            ],
        ),
        migrations.CreateModel(
            name='TodayHabitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('track_date', models.DateTimeField(verbose_name='date habit is performed')),
                ('completed', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuildHabits.Habit')),
            ],
        ),
    ]
