# Generated by Django 2.2.7 on 2019-12-06 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BuildHabits', '0002_auto_20191125_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 5, 0, tzinfo=utc), verbose_name='date habit was last changed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todayhabitlist',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 5, 0, tzinfo=utc), verbose_name='date habit was last changed'),
            preserve_default=False,
        ),
    ]
