# Generated by Django 2.2.7 on 2019-12-07 06:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BuildHabits', '0003_auto_20191206_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayhabitlist',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 5, 0, tzinfo=utc), verbose_name='date habit was last changed'),
        ),
    ]
