# Generated by Django 2.2.7 on 2019-12-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildHabits', '0005_auto_20191207_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todayhabitlist',
            name='last_modified',
        ),
    ]
